<?php

namespace Tests\Browser\StudentInfo;

use App\User;
use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class AddStudentTest extends DuskTestCase
{
    use WithFaker;
    /**
     * A Dusk test example.
     *
     * @return void
     */
    public function testLoginTest()
    {
        $this->browse(function (Browser $browser) {
            $browser
                    // ->visit('logout')
                    ->visit('/login')
                    ->type('email','admin@infixedu.com')
                    ->type('password','123456')
                    ->click('#btnsubmit')
                    ->waitForText('Welcome')
                    ->assertSee('Welcome');
        });
    }

    public function testAddStudent(){
        $this->browse(function (Browser $browser){
            $browser
             ->loginAs(User::find(1))
            ->visit('student-admission')
        
            ->click('#student_form > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div > div')
            ->pause(1000)
            ->click('#student_form > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
            ->pause(4000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(4000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(3000)
            ->type('first_name',$this->faker->firstName)
            ->type('last_name',$this->faker->lastname)
            ->click('#student_form > div > div > div > div > div:nth-child(4) > div:nth-child(3) > div > div')
            ->pause(1000)
            ->click('#student_form > div > div > div > div > div:nth-child(4) > div:nth-child(3) > div > div > ul > li:nth-child(2)')
            ->click('#start-date-icon')
            ->pause(4000)
            ->type('date_of_birth', '07/08/2021')
            ->pause(2000)
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(1) > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(2) > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(2) > div > div > ul > li:nth-child(2)')
            ->type('caste','null')
            ->type('email_address',$this->faker->email)
            ->type('phone_number','09184093')
            ->click('#student_form > div > div > div > div > div:nth-child(6) > div.col-lg-4 > div > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(6) > div.col-lg-4 > div > div > div > ul > li:nth-child(2)')
            ->pause(3000)
            ->type('height','5')
            ->type('weight','26')
            ->attach('photo',public_path('/uploads/student/student.jpg'))
            ->pause(3000)
            ->click('#LogoPic > div > div > div.modal-header > button')
            ->type('fathers_name','KH')
            ->type('fathers_occupation','farmer')
            ->type('fathers_phone','219312')
            // ->attach('photo',public_path('/uploads/student/father.png'))      
            // ->pause(3000)
            // ->click('#FatherPic > div > div > div.modal-header > button')
            ->type('mothers_name','HS')
            ->type('mothers_occupation','HW')
            ->type('mothers_phone','934879')
            // ->attach('photo',public_path('/uploads/student/mother.jpg'))
            // ->pause(3000)
            ->click('#parent_details > div:nth-child(4) > div > div > div:nth-child(1) > label')
            ->pause(4000)
            ->type('guardians_email',$this->faker->email)
            // ->attach('photo',public_path('/uploads/student/guardian.jpg'))
            // ->pause(3000)
            // ->click('#GurdianPic > div > div > div.modal-header > button')
            ->type('guardians_address','Dhaka-bangladesh')
            ->type('permanent_address','Dhaka-Bangladesh')
            ->type('national_id_number','1948713984')
            ->type('local_id_number','3948732121')
            ->type('bank_account_number','null')
            ->type('bank_name','DBBL')
            ->type('previous_school_details','infix school')
            ->type('additional_notes','null')
            ->type('ifsc_code','123')
            ->type('document_title_1','document_title_1')
            ->type('document_title_2','document_title_2')
            ->type('document_title_3','document_title_3')
            ->type('document_title_4','document_title_4')
            ->attach('document_file_1',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_2',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_3',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_4',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->click('#_submit_btn_admission')

            ->waitFor('.toast-message',5)
            ->assertSee('Operation successful');
          
         

        });
    }

    public function testAddStudentMotherGad(){
        $this->browse(function (Browser $browser){
            $browser
            ->loginAs(User::find(1))
            ->visit('student-admission')
        
            ->click('#student_form > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div > div')
            ->pause(1000)
            ->click('#student_form > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
            ->pause(4000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(4000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(3000)
            ->type('first_name',$this->faker->firstName)
            ->type('last_name',$this->faker->lastname)
            ->click('#student_form > div > div > div > div > div:nth-child(4) > div:nth-child(3) > div > div')
            ->pause(1000)
            ->click('#student_form > div > div > div > div > div:nth-child(4) > div:nth-child(3) > div > div > ul > li:nth-child(2)')
            ->click('#start-date-icon')
            ->pause(4000)
            ->type('date_of_birth', '07/08/2021')
            ->pause(2000)
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(1) > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(2) > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(2) > div > div > ul > li:nth-child(2)')
            ->type('caste','null')
            ->type('email_address',$this->faker->email)
            ->type('phone_number','09184093')
            ->click('#student_form > div > div > div > div > div:nth-child(6) > div.col-lg-4 > div > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(6) > div.col-lg-4 > div > div > div > ul > li:nth-child(2)')
            ->pause(3000)
            ->type('height','5')
            ->type('weight','26')
            ->attach('photo',public_path('/uploads/student/student.jpg'))
            ->pause(3000)
            ->click('#LogoPic > div > div > div.modal-header > button')
            ->type('fathers_name','KH')
            ->type('fathers_occupation','farmer')
            ->type('fathers_phone','219312')
            // ->attach('photo',public_path('/uploads/student/father.png'))      
            // ->pause(3000)
            // ->click('#FatherPic > div > div > div.modal-header > button')
            ->type('mothers_name','HS')
            ->type('mothers_occupation','HW')
            ->type('mothers_phone','934879')
            // ->attach('photo',public_path('/uploads/student/mother.jpg'))
            // ->pause(3000)
            ->click('#parent_details > div:nth-child(4) > div > div > div:nth-child(2) > label')
            ->pause(4000)
            ->type('guardians_email',$this->faker->email)
            // ->attach('photo',public_path('/uploads/student/guardian.jpg'))
            // ->pause(3000)
            // ->click('#GurdianPic > div > div > div.modal-header > button')
            ->type('guardians_address','Dhaka-bangladesh')
            ->type('permanent_address','Dhaka-Bangladesh')
            ->type('national_id_number','1948713984')
            ->type('local_id_number','3948732121')
            ->type('bank_account_number','null')
            ->type('bank_name','DBBL')
            ->type('previous_school_details','infix school')
            ->type('additional_notes','null')
            ->type('ifsc_code','123')
            ->type('document_title_1','document_title_1')
            ->type('document_title_2','document_title_2')
            ->type('document_title_3','document_title_3')
            ->type('document_title_4','document_title_4')
            ->attach('document_file_1',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_2',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_3',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_4',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->click('#_submit_btn_admission')

            ->waitFor('.toast-message',5)
            ->assertSee('Operation successful');
          
          
         

        });
    }

    public function testAddStudentOtherGarOne(){
        $this->browse(function (Browser $browser){
            $browser
            ->loginAs(User::find(1))
            ->visit('student-admission')
        
            ->click('#student_form > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div > div')
            ->pause(1000)
            ->click('#student_form > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
            ->pause(4000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(4000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(3000)
            ->type('first_name',$this->faker->firstName)
            ->type('last_name',$this->faker->lastname)
            ->click('#student_form > div > div > div > div > div:nth-child(4) > div:nth-child(3) > div > div')
            ->pause(1000)
            ->click('#student_form > div > div > div > div > div:nth-child(4) > div:nth-child(3) > div > div > ul > li:nth-child(2)')
            ->click('#start-date-icon')
            ->pause(4000)
            ->type('date_of_birth', '07/08/2021')
            ->pause(2000)
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(1) > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(2) > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(2) > div > div > ul > li:nth-child(2)')
            ->type('caste','null')
            ->type('email_address',$this->faker->email)
            ->type('phone_number','09184093')
            ->click('#student_form > div > div > div > div > div:nth-child(6) > div.col-lg-4 > div > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(6) > div.col-lg-4 > div > div > div > ul > li:nth-child(2)')
            ->pause(3000)
            ->type('height','5')
            ->type('weight','26')
            ->attach('photo',public_path('/uploads/student/student.jpg'))
            ->pause(3000)
            ->click('#LogoPic > div > div > div.modal-header > button')
            ->type('fathers_name','KH')
            ->type('fathers_occupation','farmer')
            ->type('fathers_phone','219312')
            // ->attach('photo',public_path('/uploads/student/father.png'))      
            // ->pause(3000)
            // ->click('#FatherPic > div > div > div.modal-header > button')
            ->type('mothers_name','HS')
            ->type('mothers_occupation','HW')
            ->type('mothers_phone','934879')
            // ->attach('photo',public_path('/uploads/student/mother.jpg'))
            // ->pause(3000)
            // ->click('#parent_details > div:nth-child(4) > div > div > div:nth-child(1) > label')
            ->pause(4000)
            ->type('guardians_name',$this->faker->name)
            ->type('guardians_email',$this->faker->email)
            // ->attach('photo',public_path('/uploads/student/guardian.jpg'))
            // ->pause(3000)
            // ->click('#GurdianPic > div > div > div.modal-header > button')
            ->type('guardians_address','Dhaka-bangladesh')
            ->type('permanent_address','Dhaka-Bangladesh')
            ->type('national_id_number','1948713984')
            ->type('local_id_number','3948732121')
            ->type('bank_account_number','null')
            ->type('bank_name','DBBL')
            ->type('previous_school_details','infix school')
            ->type('additional_notes','null')
            ->type('ifsc_code','123')
            ->type('document_title_1','document_title_1')
            ->type('document_title_2','document_title_2')
            ->type('document_title_3','document_title_3')
            ->type('document_title_4','document_title_4')
            ->attach('document_file_1',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_2',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_3',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_4',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->click('#_submit_btn_admission')

            ->waitFor('.toast-message',5)
            ->assertSee('Operation successful');
          

        });
    }

    public function testAddStudentOtherGar(){
        $this->browse(function (Browser $browser){
            $browser
            ->loginAs(User::find(1))
            ->visit('student-admission')
        
            ->click('#student_form > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div > div')
            ->pause(1000)
            ->click('#student_form > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
            ->pause(4000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(4000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(3000)
            ->type('first_name',$this->faker->firstName)
            ->type('last_name',$this->faker->lastname)
            ->click('#student_form > div > div > div > div > div:nth-child(4) > div:nth-child(3) > div > div')
            ->pause(1000)
            ->click('#student_form > div > div > div > div > div:nth-child(4) > div:nth-child(3) > div > div > ul > li:nth-child(2)')
            ->click('#start-date-icon')
            ->pause(4000)
            ->type('date_of_birth', '07/08/2021')
            ->pause(2000)
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(1) > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(1) > div > div > ul > li:nth-child(2)')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(2) > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(5) > div:nth-child(2) > div > div > ul > li:nth-child(2)')
            ->type('caste','null')
            ->type('email_address',$this->faker->email)
            ->type('phone_number','09184093')
            ->click('#student_form > div > div > div > div > div:nth-child(6) > div.col-lg-4 > div > div > div')
            ->click('#student_form > div > div > div > div > div:nth-child(6) > div.col-lg-4 > div > div > div > ul > li:nth-child(2)')
            ->pause(3000)
            ->type('height','5')
            ->type('weight','26')
            ->attach('photo',public_path('/uploads/student/student.jpg'))
            ->pause(3000)
            ->click('#LogoPic > div > div > div.modal-header > button')
            ->type('fathers_name','KH')
            ->type('fathers_occupation','farmer')
            ->type('fathers_phone','219312')
            // ->attach('photo',public_path('/uploads/student/father.png'))      
            // ->pause(3000)
            // ->click('#FatherPic > div > div > div.modal-header > button')
            ->type('mothers_name','HS')
            ->type('mothers_occupation','HW')
            ->type('mothers_phone','934879')
            // ->attach('photo',public_path('/uploads/student/mother.jpg'))
            // ->pause(3000)
            // ->click('#parent_details > div:nth-child(4) > div > div > div:nth-child(1) > label')
            ->pause(4000)
            ->type('guardians_name',$this->faker->name)
            ->type('guardians_email',$this->faker->email)
            // ->attach('photo',public_path('/uploads/student/guardian.jpg'))
            // ->pause(3000)
            // ->click('#GurdianPic > div > div > div.modal-header > button')
            ->type('guardians_address','Dhaka-bangladesh')
            ->type('permanent_address','Dhaka-Bangladesh')
            ->type('national_id_number','1948713984')
            ->type('local_id_number','3948732121')
            ->type('bank_account_number','null')
            ->type('bank_name','DBBL')
            ->type('previous_school_details','infix school')
            ->type('additional_notes','null')
            ->type('ifsc_code','123')
            ->type('document_title_1','document_title_1')
            ->type('document_title_2','document_title_2')
            ->type('document_title_3','document_title_3')
            ->type('document_title_4','document_title_4')
            ->attach('document_file_1',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_2',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_3',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->attach('document_file_4',public_path('/uploads/student/document/1.pdf'))
            ->pause(3000)
            ->click('#_submit_btn_admission')

            ->waitFor('.toast-message',5)
            ->assertSee('Operation successful');
          

        });
    }
    public function testImportStudent(){
        $this->browse(function (Browser $browser){
            $browser
            ->visit('student-admission')
            ->click('#main-content > section.admin-visitor-area.up_st_admin_visitor > div > div > div.offset-lg-3.col-lg-3.text-right.mb-20.col-sm-6 > a')
            ->assertSee('Student Import')
            ->click('#student_form > div > div > div > div > div.row.mb-40.mt-30 > div:nth-child(1) > div > div')
            ->click('#student_form > div > div > div > div > div.row.mb-40.mt-30 > div:nth-child(1) > div > div > ul > li:nth-child(2)')
            ->pause(3000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#class-div > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(3000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control')
            ->pause(1000)
            ->click('#sectionStudentDiv > div.nice-select.niceSelect.w-100.bb.form-control.open > ul > li:nth-child(2)')
            ->pause(2000)
            ->attach('file',public_path('students.xlsx'))
            ->pause(1000)
            ->click('#student_form > div > div > div > div > div.row.mt-40 > div > button')
           ->waitFor('.toast-message',5)
           ->assertSee('Operation successful');
          
        });
    }

 
}
